In [1]:
import pandas as pd
import numpy as np
import datetime
import random
import json

In [2]:
def strTimeProp(start, end, format, prop):

    stime = time.mktime(time.strptime(start, format))
    etime = time.mktime(time.strptime(end, format))

    ptime = stime + prop * (etime - stime)

    return time.strftime(format, time.localtime(ptime))


def randomDate(start, end, prop):
    return strTimeProp(start, end, '%d/%m/%Y', prop)

In [63]:
id = [i for i in range(1, 101)]
type = [random.choice(['SIRS', 'organic_disfunction']) for i in range(100)]
description = [None for i in range(100)] 
url = [None for i in range(100)]
pacient_id = [i for i in range(1, 101)]
user_id = [random.randrange(10, 15) for i in range(100)]
created_at = [datetime.datetime.now() for i in range(100)]
updated_at = [datetime.datetime.now() for i in range(100)]

In [64]:
df = pd.DataFrame({
    'id' : id,
    'type' : type,
    'description' : description,
    'url' : url,
    'pacient_id' : pacient_id,
    'user_id' : user_id,
    'created_at' : created_at,
    'updated_at' : updated_at
})

In [65]:
df

,id,type,description,url,pacient_id,user_id,created_at,updated_at
0,1,SIRS,None,None,1,13,2019-03-31 08:28:03.860386,2019-03-31 08:28:03.860565
1,2,organic_disfunction,None,None,2,11,2019-03-31 08:28:03.860392,2019-03-31 08:28:03.860567
2,3,organic_disfunction,None,None,3,14,2019-03-31 08:28:03.860393,2019-03-31 08:28:03.860568
3,4,organic_disfunction,None,None,4,12,2019-03-31 08:28:03.860394,2019-03-31 08:28:03.860569
4,5,organic_disfunction,None,None,5,14,2019-03-31 08:28:03.860395,2019-03-31 08:28:03.860570
5,6,organic_disfunction,None,None,6,14,2019-03-31 08:28:03.860396,2019-03-31 08:28:03.860571
6,7,organic_disfunction,None,None,7,13,2019-03-31 08:28:03.860397,2019-03-31 08:28:03.860572
7,8,organic_disfunction,None,None,8,11,2019-03-31 08:28:03.860398,2019-03-31 08:28:03.860573
8,9,organic_disfunction,None,None,9,13,2019-03-31 08:28:03.860399,2019-03-31 08:28:03.860574
9,10,SIRS,None,None,10,12,2019-03-31 08:28:03.860400,2019-03-31 08:28:03.860575
10,11,organic_disfunction,None,None,11,12,2019-03-31 08:28:03.860401,2019-03-31 08:28:03.860576
11,12,organic_disfunction,None,None,12,12,2019-03-31 08:28:03.860402,2019-03-31 08:28:03.860577
12,13,SIRS,None,None,13,14,2019-03-31 08:28:03.860403,2019-03-31 08:28:03.860578
13,14,SIRS,None,None,14,11,2019-03-31 08:28:03.860404,2019-03-31 08:28:03.860579
14,15,organic_disfunction,None,None,15,11,2019-03-31 08:28:03.860405,2019-03-31 08:28:03.860580
15,16,organic_disfunction,None,None,16,11,2019-03-31 08:28:03.860406,2019-03-31 08:28:03.860581
16,17,organic_disfunction,None,None,17,11,2019-03-31 08:28:03.860407,2019-03-31 08:28:03.860582
17,18,organic_disfunction,None,None,18,10,2019-03-31 08:28:03.860408,2019-03-31 08:28:03.860583
18,19,organic_disfunction,None,None,19,11,2019-03-31 08:28:03.860409,2019-03-31 08:28:03.860584
19,20,SIRS,None,None,20,14,2019-03-31 08:28:03.860410,2019-03-31 08:28:03.860585
20,21,SIRS,None,None,21,10,2019-03-31 08:28:03.860411,2019-03-31 08:28:03.860586
21,22,SIRS,None,None,22,10,2019-03-31 08:28:03.860412,2019-03-31 08:28:03.860587
22,23,SIRS,None,None,23,12,2019-03-31 08:28:03.860413,2019-03-31 08:28:03.860588
23,24,SIRS,None,None,24,14,2019-03-31 08:28:03.860414,2019-03-31 08:28:03.860589
24,25,organic_disfunction,None,None,25,12,2019-03-31 08:28:03.860415,2019-03-31 08:28:03.860590
25,26,organic_disfunction,None,None,26,11,2019-03-31 08:28:03.860416,2019-03-31 08:28:03.860591
26,27,SIRS,None,None,27,11,2019-03-31 08:28:03.860417,2019-03-31 08:28:03.860592
27,28,organic_disfunction,None,None,28,11,2019-03-31 08:28:03.860418,2019-03-31 08:28:03.860593
28,29,SIRS,None,None,29,10,2019-03-31 08:28:03.860419,2019-03-31 08:28:03.860593
29,30,SIRS,None,None,30,12,2019-03-31 08:28:03.860419,2019-03-31 08:28:03.860594
...,...,...,...,...,...,...,...,...
70,71,SIRS,None,None,71,14,2019-03-31 08:28:03.860458,2019-03-31 08:28:03.860633
71,72,organic_disfunction,None,None,72,13,2019-03-31 08:28:03.860459,2019-03-31 08:28:03.860634
72,73,organic_disfunction,None,None,73,11,2019-03-31 08:28:03.860460,2019-03-31 08:28:03.860635
73,74,SIRS,None,None,74,10,2019-03-31 08:28:03.860462,2019-03-31 08:28:03.860637
74,75,SIRS,None,None,75,10,2019-03-31 08:28:03.860463,2019-03-31 08:28:03.860638
75,76,organic_disfunction,None,None,76,10,2019-03-31 08:28:03.860464,2019-03-31 08:28:03.860639
76,77,organic_disfunction,None,None,77,10,2019-03-31 08:28:03.860465,2019-03-31 08:28:03.860639
77,78,SIRS,None,None,78,11,2019-03-31 08:28:03.860466,2019-03-31 08:28:03.860640
78,79,SIRS,None,None,79,11,2019-03-31 08:28:03.860466,2019-03-31 08:28:03.860641
79,80,organic_disfunction,None,None,80,12,2019-03-31 08:28:03.860467,2019-03-31 08:28:03.860642
80,81,organic_disfunction,None,None,81,10,2019-03-31 08:28:03.860468,2019-03-31 08:28:03.860643
81,82,organic_disfunction,None,None,82,13,2019-03-31 08:28:03.860469,2019-03-31 08:28:03.860644
82,83,organic_disfunction,None,None,83,10,2019-03-31 08:28:03.860470,2019-03-31 08:28:03.860645
83,84,organic_disfunction,None,None,84,10,2019-03-31 08:28:03.860471,2019-03-31 08:28:03.860646
84,85,SIRS,None,None,85,12,2019-03-31 08:28:03.860472,2019-03-31 08:28:03.860647
85,86,organic_disfunction,None,None,86,11,2019-03-31 08:28:03.860473,2019-03-31 08:28:03.860648
86,87,SIRS,None,None,87,13,2019-03-31 08:28:03.860474,2019-03-31 08:28:03.860649
87,88,organic_disfunction,None,None,88,13,2019-03-31 08:28:03.860475,2019-03-31 08:28:03.860650
88,89,organic_disfunction,None,None,89,10,2019-03-31 08:28:03.860476,2019-03-31 08:28:03.860650
89,90,SIRS,None,None,90,13,2019-03-31 08:28:03.860478,2019-03-31 08:28:03.860652
90,91,organic_disfunction,None,None,91,13,2019-03-31 08:28:03.860478,2019-03-31 08:28:03.860653
91,92,organic_disfunction,None,None,92,11,2019-03-31 08:28:03.860479,2019-03-31 08:28:03.860654
92,93,SIRS,None,None,93,11,2019-03-31 08:28:03.860480,2019-03-31 08:28:03.860655
93,94,SIRS,None,None,94,10,2019-03-31 08:28:03.860481,2019-03-31 08:28:03.860656
94,95,organic_disfunction,None,None,95,13,2019-03-31 08:28:03.860482,2019-03-31 08:28:03.860657
95,96,organic_disfunction,None,None,96,10,2019-03-31 08:28:03.860483,2019-03-31 08:28:03.860658
96,97,organic_disfunction,None,None,97,12,2019-03-31 08:28:03.860484,2019-03-31 08:28:03.860659
97,98,organic_disfunction,None,None,98,13,2019-03-31 08:28:03.860485,2019-03-31 08:28:03.860659
98,99,organic_disfunction,None,None,99,11,2019-03-31 08:28:03.860486,2019-03-31 08:28:03.860660
99,100,SIRS,None,None,100,11,2019-03-31 08:28:03.860487,2019-03-31 08:28:03.860661

In [66]:
df.to_csv('outcome.csv')

In [56]:
pacient = pd.read_csv('pacient.csv')
pacient

,Unnamed: 0,id,name,birth_date,taxpayer_registry,registration_completed,gender,mothers_name,image_url,registration_completed_at,created_at,updated_at
0,0,1,Marissa Saunders,19/03/1997,16351923776,0,M,Mary Davis,NaN,2019-03-31 06:51:41.133165,2019-03-31 06:51:41.133247,2019-03-31 06:51:41.133319
1,1,2,Jason Thorpe,11/09/1968,27443036779,1,F,Betty Barnett,NaN,2019-03-31 06:51:41.133168,2019-03-31 06:51:41.133248,2019-03-31 06:51:41.133320
2,2,3,Laura Criswell,22/06/1993,43438722621,1,M,Susie Tice,NaN,2019-03-31 06:51:41.133169,2019-03-31 06:51:41.133249,2019-03-31 06:51:41.133321
3,3,4,Dorothy Kramer,21/02/1992,49505340521,0,F,Barbara Kirsch,NaN,2019-03-31 06:51:41.133169,2019-03-31 06:51:41.133249,2019-03-31 06:51:41.133321
4,4,5,Dewayne Skelly,07/01/1951,29881716914,1,M,Sharon Ramirez,NaN,2019-03-31 06:51:41.133169,2019-03-31 06:51:41.133249,2019-03-31 06:51:41.133322
5,5,6,Annita Oleary,30/11/1961,47113841341,0,M,Lottie Rodriquez,NaN,2019-03-31 06:51:41.133170,2019-03-31 06:51:41.133250,2019-03-31 06:51:41.133322
6,6,7,Stephanie Miller,26/12/1958,15188879600,0,F,Debra Copas,NaN,2019-03-31 06:51:41.133170,2019-03-31 06:51:41.133250,2019-03-31 06:51:41.133323
7,7,8,Jamal Jackson,27/03/1982,36485634000,1,F,Ashley Olmos,NaN,2019-03-31 06:51:41.133170,2019-03-31 06:51:41.133250,2019-03-31 06:51:41.133323
8,8,9,Flora Hocker,27/06/1967,33997537130,0,M,Christine Mcallister,NaN,2019-03-31 06:51:41.133171,2019-03-31 06:51:41.133250,2019-03-31 06:51:41.133324
9,9,10,Pat Rhyne,26/07/1941,35633808304,1,M,Lisa Allred,NaN,2019-03-31 06:51:41.133171,2019-03-31 06:51:41.133251,2019-03-31 06:51:41.133324
10,10,11,Joseph Turpin,08/02/1970,42155548548,0,F,Hazel Cooper,NaN,2019-03-31 06:51:41.133171,2019-03-31 06:51:41.133251,2019-03-31 06:51:41.133325
11,11,12,Jennifer Sandler,02/07/1971,27966299553,1,F,Tia Polo,NaN,2019-03-31 06:51:41.133172,2019-03-31 06:51:41.133252,2019-03-31 06:51:41.133325
12,12,13,Joe Carrick,28/03/1960,34106148924,0,F,Sarah Ashpole,NaN,2019-03-31 06:51:41.133172,2019-03-31 06:51:41.133252,2019-03-31 06:51:41.133326
13,13,14,Jennifer Smith,27/12/1954,27658635431,0,F,Regina Kennan,NaN,2019-03-31 06:51:41.133172,2019-03-31 06:51:41.133252,2019-03-31 06:51:41.133326
14,14,15,Barbara Dorn,09/08/1973,40179663903,1,F,Mary Moore,NaN,2019-03-31 06:51:41.133173,2019-03-31 06:51:41.133252,2019-03-31 06:51:41.133327
15,15,16,David Pratt,25/09/1941,42800923177,1,M,Judy Gunter,NaN,2019-03-31 06:51:41.133173,2019-03-31 06:51:41.133253,2019-03-31 06:51:41.133327
16,16,17,Glen Robinson,13/05/1949,26032441532,0,M,Rebecca Ayala,NaN,2019-03-31 06:51:41.133173,2019-03-31 06:51:41.133253,2019-03-31 06:51:41.133328
17,17,18,Alberto Waller,08/03/1943,24126767467,1,F,Blanche Scarborough,NaN,2019-03-31 06:51:41.133174,2019-03-31 06:51:41.133253,2019-03-31 06:51:41.133328
18,18,19,Marlene Simpson,12/05/1993,31634181734,0,M,Louise Roudabush,NaN,2019-03-31 06:51:41.133174,2019-03-31 06:51:41.133254,2019-03-31 06:51:41.133329
19,19,20,Courtney Camp,10/08/1951,19690339637,1,M,Betsy Tribbett,NaN,2019-03-31 06:51:41.133174,2019-03-31 06:51:41.133254,2019-03-31 06:51:41.133329
20,20,21,Jesus Moore,17/11/1994,45703190218,1,F,Amber Smith,NaN,2019-03-31 06:51:41.133174,2019-03-31 06:51:41.133254,2019-03-31 06:51:41.133330
21,21,22,David Hurley,11/09/1993,23919421951,1,F,Lynn Quirk,NaN,2019-03-31 06:51:41.133175,2019-03-31 06:51:41.133255,2019-03-31 06:51:41.133330
22,22,23,Sharon Hunter,28/03/1960,44373743231,1,F,Stacey Dage,NaN,2019-03-31 06:51:41.133175,2019-03-31 06:51:41.133255,2019-03-31 06:51:41.133331
23,23,24,John Pentz,07/04/1988,42204286506,0,M,Betty Butler,NaN,2019-03-31 06:51:41.133175,2019-03-31 06:51:41.133255,2019-03-31 06:51:41.133331
24,24,25,James Allen,22/05/1989,13402742570,0,F,Jessica Melville,NaN,2019-03-31 06:51:41.133176,2019-03-31 06:51:41.133256,2019-03-31 06:51:41.133332
25,25,26,Michael Wahl,15/05/1984,43602360340,0,M,Ruth Guess,NaN,2019-03-31 06:51:41.133176,2019-03-31 06:51:41.133256,2019-03-31 06:51:41.133333
26,26,27,Maggie Williams,13/02/1945,14505066146,0,F,Joana Salvas,NaN,2019-03-31 06:51:41.133176,2019-03-31 06:51:41.133256,2019-03-31 06:51:41.133333
27,27,28,Jack Snell,27/08/1967,16012584628,1,F,Elizabeth Bridgham,NaN,2019-03-31 06:51:41.133177,2019-03-31 06:51:41.133257,2019-03-31 06:51:41.133334
28,28,29,Jennifer Ramirez,06/06/1957,38784548394,0,F,Mary Durham,NaN,2019-03-31 06:51:41.133177,2019-03-31 06:51:41.133257,2019-03-31 06:51:41.133334
29,29,30,Tina Gochenour,26/03/2003,45992994887,1,F,Marcia Holder,NaN,2019-03-31 06:51:41.133177,2019-03-31 06:51:41.133257,2019-03-31 06:51:41.133335
...,...,...,...,...,...,...,...,...,...,...,...,...
70,70,71,Ray Nero,27/08/1971,23704258083,0,M,Glenda Mcdaniel,NaN,2019-03-31 06:51:41.133190,2019-03-31 06:51:41.133270,2019-03-31 06:51:41.133348
71,71,72,Mary Shippee,31/07/1946,44017408458,1,M,Judy Ciriaco,NaN,2019-03-31 06:51:41.133191,2019-03-31 06:51:41.133271,2019-03-31 06:51:41.133348
72,72,73,Tommy Hammer,26/05/1969,25689051069,1,M,Heather Lowe,NaN,2019-03-31 06:51:41.133191,2019-03-31 06:51:41.133271,2019-03-31 06:51:41.133349
73,73,74,Karen Hulsey,20/06/1968,21850343069,1,M,Anne Brown,NaN,2019-03-31 06:51:41.133192,2019-03-31 06:51:41.133271,2019-03-31 06:51:41.133349
74,74,75,David Crosby,20/04/1947,10432523715,1,M,Edna Hoefling,NaN,2019-03-31 06:51:41.133192,2019-03-31 06:51:41.133272,2019-03-31 06:51:41.133350
75,75,76,Carlos King,24/01/1987,15935566586,1,F,Colleen Chisholm,NaN,2019-03-31 06:51:41.133192,2019-03-31 06:51:41.133272,2019-03-31 06:51:41.133350
76,76,77,Grace Lewis,22/01/1977,39070342191,0,M,Clorinda Higgins,NaN,2019-03-31 06:51:41.133193,2019-03-31 06:51:41.133272,2019-03-31 06:51:41.133350
77,77,78,Jerry Pate,04/09/1978,39503383168,0,F,Helen Simon,NaN,2019-03-31 06:51:41.133193,2019-03-31 06:51:41.133273,2019-03-31 06:51:41.133351
78,78,79,Laurel Surratt,31/07/1964,35193125289,1,M,Leticia Oxley,NaN,2019-03-31 06:51:41.133193,2019-03-31 06:51:41.133273,2019-03-31 06:51:41.133351
79,79,80,Jasper Sullivan,29/12/1958,12157223400,0,M,Alicia Garcia,NaN,2019-03-31 06:51:41.133194,2019-03-31 06:51:41.133273,2019-03-31 06:51:41.133351
80,80,81,Jessie Deoliveira,10/01/1987,38801702069,1,F,Elizabeth Edwards,NaN,2019-03-31 06:51:41.133194,2019-03-31 06:51:41.133274,2019-03-31 06:51:41.133352
81,81,82,Gregg Perry,08/06/1977,33629966021,0,M,Lois Fisher,NaN,2019-03-31 06:51:41.133194,2019-03-31 06:51:41.133274,2019-03-31 06:51:41.133352
82,82,83,Charles Marston,21/09/2000,33284335358,1,F,Carol Campbell,NaN,2019-03-31 06:51:41.133194,2019-03-31 06:51:41.133274,2019-03-31 06:51:41.133352
83,83,84,Bob Anderson,17/12/1998,29782608472,1,M,Kristen Glinski,NaN,2019-03-31 06:51:41.133195,2019-03-31 06:51:41.133275,2019-03-31 06:51:41.133352
84,84,85,Justin Dempsey,13/04/1999,32148095910,0,M,Carole Fix,NaN,2019-03-31 06:51:41.133195,2019-03-31 06:51:41.133275,2019-03-31 06:51:41.133353
85,85,86,Marth Jackson,02/03/1944,15047712468,1,F,Kathryn Norgaard,NaN,2019-03-31 06:51:41.133195,2019-03-31 06:51:41.133275,2019-03-31 06:51:41.133353
86,86,87,Nancy Ross,27/07/1959,42608737061,0,M,Patricia Dicus,NaN,2019-03-31 06:51:41.133196,2019-03-31 06:51:41.133275,2019-03-31 06:51:41.133353
87,87,88,Michael Leach,15/05/1982,19001508233,0,M,Anna Mcclure,NaN,2019-03-31 06:51:41.133196,2019-03-31 06:51:41.133276,2019-03-31 06:51:41.133354
88,88,89,Jay Moore,28/06/1994,23961141760,1,F,Myrtle Battaglia,NaN,2019-03-31 06:51:41.133196,2019-03-31 06:51:41.133276,2019-03-31 06:51:41.133354
89,89,90,Alfred Allen,01/08/1962,46674990559,1,M,Lisa Stewart,NaN,2019-03-31 06:51:41.133197,2019-03-31 06:51:41.133277,2019-03-31 06:51:41.133354
90,90,91,Lacresha Harmon,06/02/1962,44990042626,1,F,Estella Almeida,NaN,2019-03-31 06:51:41.133197,2019-03-31 06:51:41.133277,2019-03-31 06:51:41.133355
91,91,92,Reginald Sandling,27/07/1982,30345589290,1,F,Rosemary Askew,NaN,2019-03-31 06:51:41.133197,2019-03-31 06:51:41.133277,2019-03-31 06:51:41.133355
92,92,93,Leesa Lemelin,03/09/1968,10718752430,0,M,Margaret Hernandez,NaN,2019-03-31 06:51:41.133198,2019-03-31 06:51:41.133278,2019-03-31 06:51:41.133355
93,93,94,Trisha Austin,07/06/1977,41565026362,0,M,Jacqueline Bandy,NaN,2019-03-31 06:51:41.133198,2019-03-31 06:51:41.133278,2019-03-31 06:51:41.133356
94,94,95,Marietta Daniel,24/10/1971,15937052804,1,M,Pansy Doonan,NaN,2019-03-31 06:51:41.133198,2019-03-31 06:51:41.133278,2019-03-31 06:51:41.133356
95,95,96,Hilda Brenner,22/11/1951,30404770824,0,M,Lorena Morgan,NaN,2019-03-31 06:51:41.133199,2019-03-31 06:51:41.133278,2019-03-31 06:51:41.133356
96,96,97,Michael Johnson,28/11/1988,11752104662,0,F,Rita Johnson,NaN,2019-03-31 06:51:41.133199,2019-03-31 06:51:41.133279,2019-03-31 06:51:41.133357
97,97,98,Debra Strickland,06/11/1985,16797428680,1,F,Patricia Murphy,NaN,2019-03-31 06:51:41.133199,2019-03-31 06:51:41.133279,2019-03-31 06:51:41.133357
98,98,99,Jennifer Syers,23/03/1958,22634829097,0,F,Kathleen Harris,NaN,2019-03-31 06:51:41.133200,2019-03-31 06:51:41.133279,2019-03-31 06:51:41.133357
99,99,100,Willa Stone,04/11/1981,10408691797,1,F,Pamela Dobbs,NaN,2019-03-31 06:51:41.133200,2019-03-31 06:51:41.133280,2019-03-31 06:51:41.133358

In [50]:
import requests

In [51]:
resp = requests.get(url='https://sepsisguardian.planetsweb.com.br/api/user/get.php?token=9f3eb59b17f92558802189384836c7cb')

In [52]:
resp = resp.json()

In [48]:
name1 = resp['resposta'][0]['name']
name2 = resp['resposta'][1]['name'] 
name3 = resp['resposta'][2]['name'] 
name4 = resp['resposta'][3]['name']
df2 = pd.DataFrame({
    'id' : [13,12,11,10],
    'name' : [name1,name2,name3,name4]
})
df2

   id   name
0  13  Maria
1  12  Paula
2  11   João
3  10  Pedro

In [69]:
df3 =  df.merge(df2, how='inner', left_on='user_id', right_on='id')
df3

,id_x,type,description,url,pacient_id,user_id,created_at,updated_at,id_y,name
0,1,SIRS,None,None,1,13,2019-03-31 08:28:03.860386,2019-03-31 08:28:03.860565,13,Maria
1,7,organic_disfunction,None,None,7,13,2019-03-31 08:28:03.860397,2019-03-31 08:28:03.860572,13,Maria
2,9,organic_disfunction,None,None,9,13,2019-03-31 08:28:03.860399,2019-03-31 08:28:03.860574,13,Maria
3,31,SIRS,None,None,31,13,2019-03-31 08:28:03.860420,2019-03-31 08:28:03.860595,13,Maria
4,36,organic_disfunction,None,None,36,13,2019-03-31 08:28:03.860425,2019-03-31 08:28:03.860600,13,Maria
5,37,organic_disfunction,None,None,37,13,2019-03-31 08:28:03.860426,2019-03-31 08:28:03.860601,13,Maria
6,38,SIRS,None,None,38,13,2019-03-31 08:28:03.860427,2019-03-31 08:28:03.860602,13,Maria
7,45,SIRS,None,None,45,13,2019-03-31 08:28:03.860434,2019-03-31 08:28:03.860609,13,Maria
8,46,organic_disfunction,None,None,46,13,2019-03-31 08:28:03.860435,2019-03-31 08:28:03.860610,13,Maria
9,50,SIRS,None,None,50,13,2019-03-31 08:28:03.860438,2019-03-31 08:28:03.860613,13,Maria
10,51,SIRS,None,None,51,13,2019-03-31 08:28:03.860439,2019-03-31 08:28:03.860614,13,Maria
11,57,organic_disfunction,None,None,57,13,2019-03-31 08:28:03.860445,2019-03-31 08:28:03.860620,13,Maria
12,72,organic_disfunction,None,None,72,13,2019-03-31 08:28:03.860459,2019-03-31 08:28:03.860634,13,Maria
13,82,organic_disfunction,None,None,82,13,2019-03-31 08:28:03.860469,2019-03-31 08:28:03.860644,13,Maria
14,87,SIRS,None,None,87,13,2019-03-31 08:28:03.860474,2019-03-31 08:28:03.860649,13,Maria
15,88,organic_disfunction,None,None,88,13,2019-03-31 08:28:03.860475,2019-03-31 08:28:03.860650,13,Maria
16,90,SIRS,None,None,90,13,2019-03-31 08:28:03.860478,2019-03-31 08:28:03.860652,13,Maria
17,91,organic_disfunction,None,None,91,13,2019-03-31 08:28:03.860478,2019-03-31 08:28:03.860653,13,Maria
18,95,organic_disfunction,None,None,95,13,2019-03-31 08:28:03.860482,2019-03-31 08:28:03.860657,13,Maria
19,98,organic_disfunction,None,None,98,13,2019-03-31 08:28:03.860485,2019-03-31 08:28:03.860659,13,Maria
20,2,organic_disfunction,None,None,2,11,2019-03-31 08:28:03.860392,2019-03-31 08:28:03.860567,11,João
21,8,organic_disfunction,None,None,8,11,2019-03-31 08:28:03.860398,2019-03-31 08:28:03.860573,11,João
22,14,SIRS,None,None,14,11,2019-03-31 08:28:03.860404,2019-03-31 08:28:03.860579,11,João
23,15,organic_disfunction,None,None,15,11,2019-03-31 08:28:03.860405,2019-03-31 08:28:03.860580,11,João
24,16,organic_disfunction,None,None,16,11,2019-03-31 08:28:03.860406,2019-03-31 08:28:03.860581,11,João
25,17,organic_disfunction,None,None,17,11,2019-03-31 08:28:03.860407,2019-03-31 08:28:03.860582,11,João
26,19,organic_disfunction,None,None,19,11,2019-03-31 08:28:03.860409,2019-03-31 08:28:03.860584,11,João
27,26,organic_disfunction,None,None,26,11,2019-03-31 08:28:03.860416,2019-03-31 08:28:03.860591,11,João
28,27,SIRS,None,None,27,11,2019-03-31 08:28:03.860417,2019-03-31 08:28:03.860592,11,João
29,28,organic_disfunction,None,None,28,11,2019-03-31 08:28:03.860418,2019-03-31 08:28:03.860593,11,João
...,...,...,...,...,...,...,...,...,...,...
56,69,organic_disfunction,None,None,69,12,2019-03-31 08:28:03.860456,2019-03-31 08:28:03.860631,12,Paula
57,80,organic_disfunction,None,None,80,12,2019-03-31 08:28:03.860467,2019-03-31 08:28:03.860642,12,Paula
58,85,SIRS,None,None,85,12,2019-03-31 08:28:03.860472,2019-03-31 08:28:03.860647,12,Paula
59,97,organic_disfunction,None,None,97,12,2019-03-31 08:28:03.860484,2019-03-31 08:28:03.860659,12,Paula
60,18,organic_disfunction,None,None,18,10,2019-03-31 08:28:03.860408,2019-03-31 08:28:03.860583,10,Pedro
61,21,SIRS,None,None,21,10,2019-03-31 08:28:03.860411,2019-03-31 08:28:03.860586,10,Pedro
62,22,SIRS,None,None,22,10,2019-03-31 08:28:03.860412,2019-03-31 08:28:03.860587,10,Pedro
63,29,SIRS,None,None,29,10,2019-03-31 08:28:03.860419,2019-03-31 08:28:03.860593,10,Pedro
64,32,SIRS,None,None,32,10,2019-03-31 08:28:03.860421,2019-03-31 08:28:03.860596,10,Pedro
65,33,SIRS,None,None,33,10,2019-03-31 08:28:03.860422,2019-03-31 08:28:03.860597,10,Pedro
66,44,organic_disfunction,None,None,44,10,2019-03-31 08:28:03.860433,2019-03-31 08:28:03.860608,10,Pedro
67,47,organic_disfunction,None,None,47,10,2019-03-31 08:28:03.860435,2019-03-31 08:28:03.860610,10,Pedro
68,52,SIRS,None,None,52,10,2019-03-31 08:28:03.860440,2019-03-31 08:28:03.860615,10,Pedro
69,53,SIRS,None,None,53,10,2019-03-31 08:28:03.860441,2019-03-31 08:28:03.860616,10,Pedro
70,58,organic_disfunction,None,None,58,10,2019-03-31 08:28:03.860446,2019-03-31 08:28:03.860621,10,Pedro
71,60,SIRS,None,None,60,10,2019-03-31 08:28:03.860448,2019-03-31 08:28:03.860623,10,Pedro
72,63,organic_disfunction,None,None,63,10,2019-03-31 08:28:03.860451,2019-03-31 08:28:03.860626,10,Pedro
73,64,organic_disfunction,None,None,64,10,2019-03-31 08:28:03.860451,2019-03-31 08:28:03.860627,10,Pedro
74,67,SIRS,None,None,67,10,2019-03-31 08:28:03.860454,2019-03-31 08:28:03.860629,10,Pedro
75,70,SIRS,None,None,70,10,2019-03-31 08:28:03.860457,2019-03-31 08:28:03.860632,10,Pedro
76,74,SIRS,None,None,74,10,2019-03-31 08:28:03.860462,2019-03-31 08:28:03.860637,10,Pedro
77,75,SIRS,None,None,75,10,2019-03-31 08:28:03.860463,2019-03-31 08:28:03.860638,10,Pedro
78,76,organic_disfunction,None,None,76,10,2019-03-31 08:28:03.860464,2019-03-31 08:28:03.860639,10,Pedro
79,77,organic_disfunction,None,None,77,10,2019-03-31 08:28:03.860465,2019-03-31 08:28:03.860639,10,Pedro
80,81,organic_disfunction,None,None,81,10,2019-03-31 08:28:03.860468,2019-03-31 08:28:03.860643,10,Pedro
81,83,organic_disfunction,None,None,83,10,2019-03-31 08:28:03.860470,2019-03-31 08:28:03.860645,10,Pedro
82,84,organic_disfunction,None,None,84,10,2019-03-31 08:28:03.860471,2019-03-31 08:28:03.860646,10,Pedro
83,89,organic_disfunction,None,None,89,10,2019-03-31 08:28:03.860476,2019-03-31 08:28:03.860650,10,Pedro
84,94,SIRS,None,None,94,10,2019-03-31 08:28:03.860481,2019-03-31 08:28:03.860656,10,Pedro
85,96,organic_disfunction,None,None,96,10,2019-03-31 08:28:03.860483,2019-03-31 08:28:03.860658,10,Pedro

In [104]:
df5 = pd.read_csv('patient_data.csv')
df4 = df3.merge(pacient, how='left', left_on='pacient_id', right_on='id')
df4 = df4.merge(df5, how='left', left_on='pacient_id', right_on='pacient_id' )
df4

,id_x,type,description,url,pacient_id,user_id_x,created_at_x,updated_at_x,id_y,name_x,...,creatinine,pao2_fio2_relation,spo2,platelet,lactate,consciousness_status,bilirubin,user_id_y,created_at,updated_at
0,1,SIRS,None,None,1,13,2019-03-31 08:28:03.860386,2019-03-31 08:28:03.860565,13,Maria,...,2.139878,309,1,68429,0,0,1,11,2019-03-31 06:20:34.974982,2019-03-31 06:20:34.975072
1,7,organic_disfunction,None,None,7,13,2019-03-31 08:28:03.860397,2019-03-31 08:28:03.860572,13,Maria,...,2.699563,189,0,167612,1,0,1,10,2019-03-31 06:20:34.974988,2019-03-31 06:20:34.975075
2,9,organic_disfunction,None,None,9,13,2019-03-31 08:28:03.860399,2019-03-31 08:28:03.860574,13,Maria,...,1.777455,286,0,170935,0,0,0,10,2019-03-31 06:20:34.974989,2019-03-31 06:20:34.975076
3,31,SIRS,None,None,31,13,2019-03-31 08:28:03.860420,2019-03-31 08:28:03.860595,13,Maria,...,1.844966,315,0,55806,1,0,1,11,2019-03-31 06:20:34.975000,2019-03-31 06:20:34.975087
4,36,organic_disfunction,None,None,36,13,2019-03-31 08:28:03.860425,2019-03-31 08:28:03.860600,13,Maria,...,2.356678,398,1,136726,1,0,0,10,2019-03-31 06:20:34.975002,2019-03-31 06:20:34.975089
5,37,organic_disfunction,None,None,37,13,2019-03-31 08:28:03.860426,2019-03-31 08:28:03.860601,13,Maria,...,1.000401,347,0,153933,1,0,1,12,2019-03-31 06:20:34.975002,2019-03-31 06:20:34.975089
6,38,SIRS,None,None,38,13,2019-03-31 08:28:03.860427,2019-03-31 08:28:03.860602,13,Maria,...,0.896390,279,0,102103,0,0,1,10,2019-03-31 06:20:34.975003,2019-03-31 06:20:34.975090
7,45,SIRS,None,None,45,13,2019-03-31 08:28:03.860434,2019-03-31 08:28:03.860609,13,Maria,...,0.885143,293,0,64465,1,0,0,11,2019-03-31 06:20:34.975006,2019-03-31 06:20:34.975093
8,46,organic_disfunction,None,None,46,13,2019-03-31 08:28:03.860435,2019-03-31 08:28:03.860610,13,Maria,...,1.591553,350,1,148101,1,0,0,11,2019-03-31 06:20:34.975007,2019-03-31 06:20:34.975094
9,50,SIRS,None,None,50,13,2019-03-31 08:28:03.860438,2019-03-31 08:28:03.860613,13,Maria,...,2.765061,301,0,86516,1,0,1,13,2019-03-31 06:20:34.975009,2019-03-31 06:20:34.975096
10,51,SIRS,None,None,51,13,2019-03-31 08:28:03.860439,2019-03-31 08:28:03.860614,13,Maria,...,1.594233,161,0,166491,1,0,1,11,2019-03-31 06:20:34.975009,2019-03-31 06:20:34.975096
11,57,organic_disfunction,None,None,57,13,2019-03-31 08:28:03.860445,2019-03-31 08:28:03.860620,13,Maria,...,0.768968,359,0,148411,0,0,0,10,2019-03-31 06:20:34.975012,2019-03-31 06:20:34.975099
12,72,organic_disfunction,None,None,72,13,2019-03-31 08:28:03.860459,2019-03-31 08:28:03.860634,13,Maria,...,0.682598,263,1,180200,0,0,0,10,2019-03-31 06:20:34.975019,2019-03-31 06:20:34.975106
13,82,organic_disfunction,None,None,82,13,2019-03-31 08:28:03.860469,2019-03-31 08:28:03.860644,13,Maria,...,1.487752,283,1,192275,1,0,1,11,2019-03-31 06:20:34.975024,2019-03-31 06:20:34.975110
14,87,SIRS,None,None,87,13,2019-03-31 08:28:03.860474,2019-03-31 08:28:03.860649,13,Maria,...,1.097278,255,0,189349,1,0,1,13,2019-03-31 06:20:34.975026,2019-03-31 06:20:34.975113
15,88,organic_disfunction,None,None,88,13,2019-03-31 08:28:03.860475,2019-03-31 08:28:03.860650,13,Maria,...,2.812214,288,1,193136,1,0,0,11,2019-03-31 06:20:34.975026,2019-03-31 06:20:34.975113
16,90,SIRS,None,None,90,13,2019-03-31 08:28:03.860478,2019-03-31 08:28:03.860652,13,Maria,...,2.746596,319,0,146470,1,0,0,12,2019-03-31 06:20:34.975027,2019-03-31 06:20:34.975114
17,91,organic_disfunction,None,None,91,13,2019-03-31 08:28:03.860478,2019-03-31 08:28:03.860653,13,Maria,...,1.110765,376,0,126650,1,0,0,10,2019-03-31 06:20:34.975028,2019-03-31 06:20:34.975115
18,95,organic_disfunction,None,None,95,13,2019-03-31 08:28:03.860482,2019-03-31 08:28:03.860657,13,Maria,...,1.677346,273,0,180660,0,0,1,10,2019-03-31 06:20:34.975030,2019-03-31 06:20:34.975117
19,98,organic_disfunction,None,None,98,13,2019-03-31 08:28:03.860485,2019-03-31 08:28:03.860659,13,Maria,...,1.159881,152,1,161680,1,0,1,11,2019-03-31 06:20:34.975031,2019-03-31 06:20:34.975118
20,2,organic_disfunction,None,None,2,11,2019-03-31 08:28:03.860392,2019-03-31 08:28:03.860567,11,João,...,2.493227,380,1,84274,1,0,0,11,2019-03-31 06:20:34.974986,2019-03-31 06:20:34.975073
21,8,organic_disfunction,None,None,8,11,2019-03-31 08:28:03.860398,2019-03-31 08:28:03.860573,11,João,...,2.679967,274,0,87560,0,0,0,12,2019-03-31 06:20:34.974989,2019-03-31 06:20:34.975076
22,14,SIRS,None,None,14,11,2019-03-31 08:28:03.860404,2019-03-31 08:28:03.860579,11,João,...,1.123768,355,1,153197,1,0,0,11,2019-03-31 06:20:34.974992,2019-03-31 06:20:34.975079
23,15,organic_disfunction,None,None,15,11,2019-03-31 08:28:03.860405,2019-03-31 08:28:03.860580,11,João,...,0.569401,269,1,77017,1,0,1,11,2019-03-31 06:20:34.974992,2019-03-31 06:20:34.975079
24,16,organic_disfunction,None,None,16,11,2019-03-31 08:28:03.860406,2019-03-31 08:28:03.860581,11,João,...,0.717416,322,0,147934,0,0,0,13,2019-03-31 06:20:34.974993,2019-03-31 06:20:34.975080
25,17,organic_disfunction,None,None,17,11,2019-03-31 08:28:03.860407,2019-03-31 08:28:03.860582,11,João,...,1.729361,193,0,102700,1,0,0,10,2019-03-31 06:20:34.974993,2019-03-31 06:20:34.975080
26,19,organic_disfunction,None,None,19,11,2019-03-31 08:28:03.860409,2019-03-31 08:28:03.860584,11,João,...,0.874960,222,1,162711,0,0,0,12,2019-03-31 06:20:34.974994,2019-03-31 06:20:34.975081
27,26,organic_disfunction,None,None,26,11,2019-03-31 08:28:03.860416,2019-03-31 08:28:03.860591,11,João,...,1.496049,268,1,132942,0,0,0,13,2019-03-31 06:20:34.974997,2019-03-31 06:20:34.975084
28,27,SIRS,None,None,27,11,2019-03-31 08:28:03.860417,2019-03-31 08:28:03.860592,11,João,...,2.813938,340,0,118044,1,0,0,11,2019-03-31 06:20:34.974998,2019-03-31 06:20:34.975085
29,28,organic_disfunction,None,None,28,11,2019-03-31 08:28:03.860418,2019-03-31 08:28:03.860593,11,João,...,2.316084,288,1,143010,0,0,1,12,2019-03-31 06:20:34.974998,2019-03-31 06:20:34.975085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,69,organic_disfunction,None,None,69,12,2019-03-31 08:28:03.860456,2019-03-31 08:28:03.860631,12,Paula,...,1.980043,267,0,178925,0,0,1,11,2019-03-31 06:20:34.975017,2019-03-31 06:20:34.975104
57,80,organic_disfunction,None,None,80,12,2019-03-31 08:28:03.860467,2019-03-31 08:28:03.860642,12,Paula,...,1.381869,288,0,142672,0,0,0,13,2019-03-31 06:20:34.975023,2019-03-31 06:20:34.975110
58,85,SIRS,None,None,85,12,2019-03-31 08:28:03.860472,2019-03-31 08:28:03.860647,12,Paula,...,2.765933,253,0,137751,0,0,1,10,2019-03-31 06:20:34.975025,2019-03-31 06:20:34.975112
59,97,organic_disfunction,None,None,97,12,2019-03-31 08:28:03.860484,2019-03-31 08:28:03.860659,12,Paula,...,1.686888,327,1,76228,1,0,1,13,2019-03-31 06:20:34.975031,2019-03-31 06:20:34.975117
60,18,organic_disfunction,None,None,18,10,2019-03-31 08:28:03.860408,2019-03-31 08:28:03.860583,10,Pedro,...,2.955357,275,1,85890,0,0,1,13,2019-03-31 06:20:34.974994,2019-03-31 06:20:34.975081
61,21,SIRS,None,None,21,10,2019-03-31 08:28:03.860411,2019-03-31 08:28:03.860586,10,Pedro,...,0.755007,237,0,186962,0,0,0,13,2019-03-31 06:20:34.974995,2019-03-31 06:20:34.975082
62,22,SIRS,None,None,22,10,2019-03-31 08:28:03.860412,2019-03-31 08:28:03.860587,10,Pedro,...,2.856227,207,1,151393,0,0,0,12,2019-03-31 06:20:34.974995,2019-03-31 06:20:34.975082
63,29,SIRS,None,None,29,10,2019-03-31 08:28:03.860419,2019-03-31 08:28:03.860593,10,Pedro,...,2.404739,345,1,113585,0,0,1,12,2019-03-31 06:20:34.974999,2019-03-31 06:20:34.975086
64,32,SIRS,None,None,32,10,2019-03-31 08:28:03.860421,2019-03-31 08:28:03.860596,10,Pedro,...,2.439536,208,1,184335,1,0,1,10,2019-03-31 06:20:34.975000,2019-03-31 06:20:34.975087
65,33,SIRS,None,None,33,10,2019-03-31 08:28:03.860422,2019-03-31 08:28:03.860597,10,Pedro,...,1.398800,256,1,128786,1,0,0,11,2019-03-31 06:20:34.975000,2019-03-31 06:20:34.975088
66,44,organic_disfunction,None,None,44,10,2019-03-31 08:28:03.860433,2019-03-31 08:28:03.860608,10,Pedro,...,2.056818,175,1,132070,1,0,1,10,2019-03-31 06:20:34.975006,2019-03-31 06:20:34.975093
67,47,organic_disfunction,None,None,47,10,2019-03-31 08:28:03.860435,2019-03-31 08:28:03.860610,10,Pedro,...,0.767348,233,0,191845,0,0,0,10,2019-03-31 06:20:34.975007,2019-03-31 06:20:34.975094
68,52,SIRS,None,None,52,10,2019-03-31 08:28:03.860440,2019-03-31 08:28:03.860615,10,Pedro,...,2.423835,264,0,150877,1,0,1,13,2019-03-31 06:20:34.975010,2019-03-31 06:20:34.975096
69,53,SIRS,None,None,53,10,2019-03-31 08:28:03.860441,2019-03-31 08:28:03.860616,10,Pedro,...,2.865026,168,0,124490,0,0,1,12,2019-03-31 06:20:34.975010,2019-03-31 06:20:34.975097
70,58,organic_disfunction,None,None,58,10,2019-03-31 08:28:03.860446,2019-03-31 08:28:03.860621,10,Pedro,...,2.023256,317,0,85747,1,0,1,10,2019-03-31 06:20:34.975012,2019-03-31 06:20:34.975099
71,60,SIRS,None,None,60,10,2019-03-31 08:28:03.860448,2019-03-31 08:28:03.860623,10,Pedro,...,1.289009,354,0,113752,0,0,0,11,2019-03-31 06:20:34.975013,2019-03-31 06:20:34.975100
72,63,organic_disfunction,None,None,63,10,2019-03-31 08:28:03.860451,2019-03-31 08:28:03.860626,10,Pedro,...,1.654382,176,1,120448,0,0,0,11,2019-03-31 06:20:34.975015,2019-03-31 06:20:34.975102
73,64,organic_disfunction,None,None,64,10,2019-03-31 08:28:03.860451,2019-03-31 08:28:03.860627,10,Pedro,...,2.636457,364,0,50484,0,0,0,13,2019-03-31 06:20:34.975015,2019-03-31 06:20:34.975102
74,67,SIRS,None,None,67,10,2019-03-31 08:28:03.860454,2019-03-31 08:28:03.860629,10,Pedro,...,0.901816,261,1,55183,1,0,1,10,2019-03-31 06:20:34.975016,2019-03-31 06:20:34.975103
75,70,SIRS,None,None,70,10,2019-03-31 08:28:03.860457,2019-03-31 08:28:03.860632,10,Pedro,...,2.107568,371,1,142128,1,0,1,12,2019-03-31 06:20:34.975018,2019-03-31 06:20:34.975105
76,74,SIRS,None,None,74,10,2019-03-31 08:28:03.860462,2019-03-31 08:28:03.860637,10,Pedro,...,0.993548,328,0,57439,0,0,0,13,2019-03-31 06:20:34.975020,2019-03-31 06:20:34.975107
77,75,SIRS,None,None,75,10,2019-03-31 08:28:03.860463,2019-03-31 08:28:03.860638,10,Pedro,...,1.199391,162,1,56557,1,0,0,12,2019-03-31 06:20:34.975020,2019-03-31 06:20:34.975107
78,76,organic_disfunction,None,None,76,10,2019-03-31 08:28:03.860464,2019-03-31 08:28:03.860639,10,Pedro,...,1.553119,325,0,96122,0,0,0,10,2019-03-31 06:20:34.975021,2019-03-31 06:20:34.975108
79,77,organic_disfunction,None,None,77,10,2019-03-31 08:28:03.860465,2019-03-31 08:28:03.860639,10,Pedro,...,1.446814,313,1,154821,1,0,1,13,2019-03-31 06:20:34.975021,2019-03-31 06:20:34.975108
80,81,organic_disfunction,None,None,81,10,2019-03-31 08:28:03.860468,2019-03-31 08:28:03.860643,10,Pedro,...,1.747665,351,1,187287,0,0,1,12,2019-03-31 06:20:34.975023,2019-03-31 06:20:34.975110
81,83,organic_disfunction,None,None,83,10,2019-03-31 08:28:03.860470,2019-03-31 08:28:03.860645,10,Pedro,...,0.792140,218,0,75791,0,0,1,12,2019-03-31 06:20:34.975024,2019-03-31 06:20:34.975111
82,84,organic_disfunction,None,None,84,10,2019-03-31 08:28:03.860471,2019-03-31 08:28:03.860646,10,Pedro,...,1.738677,251,1,112137,0,0,0,13,2019-03-31 06:20:34.975025,2019-03-31 06:20:34.975111
83,89,organic_disfunction,None,None,89,10,2019-03-31 08:28:03.860476,2019-03-31 08:28:03.860650,10,Pedro,...,0.613782,348,0,122493,0,0,0,10,2019-03-31 06:20:34.975027,2019-03-31 06:20:34.975114
84,94,SIRS,None,None,94,10,2019-03-31 08:28:03.860481,2019-03-31 08:28:03.860656,10,Pedro,...,1.439252,199,1,91279,0,0,1,12,2019-03-31 06:20:34.975029,2019-03-31 06:20:34.975116
85,96,organic_disfunction,None,None,96,10,2019-03-31 08:28:03.860483,2019-03-31 08:28:03.860658,10,Pedro,...,2.337400,281,1,199430,1,0,0,11,2019-03-31 06:20:34.975030,2019-03-31 06:20:34.975117

In [105]:
df4['description'] = df4['description'].fillna(value=df4.name_x+' o paciente '+df4.name_y+' precisa de você !')

In [106]:
df4
df4.to_csv('outcome.csv')

In [118]:
features = df4.columns.difference(['type','birth_date','created_at_x','created_at_y',
'updated_at_x','updated_at_y','registration_completed_at','description','name_x','name_y',
'taxpayer_registry','mothers_name','gender','image_url','url','id_x','id_y','pacient_id','user_id','created_at','updated_at',
'Unnamed: 0_x', 'Unnamed: 0_y', 'user_id_x', 'user_id_y','registration_completed'])

ft = df4[features].values
outcome = df4['type'].values
features

Index(['average_arterial_pressure', 'bilirubin', 'cardio_frequency',
       'central_temperature', 'consciousness_status', 'creatinine', 'lactate',
       'left_deviation', 'oliguria', 'pao2_fio2_relation', 'platelet',
       'resp_frequency', 'sistolic_arterial_pressure', 'spo2',
       'total_leucocyto'],
      dtype='object')

In [147]:
from sklearn.tree import DecisionTreeClassifier

classifier_dt = DecisionTreeClassifier(random_state=1986, criterion='entropy', max_depth=25, min_samples_leaf = 35)
classifier_dt.fit(ft, outcome)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=25,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=35, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1986,
            splitter='best')

In [148]:
central_temperature = [random.randrange(35, 41) for i in range(1)]
cardio_frequency = [random.randrange(60, 180) for i in range(1)]
resp_frequency = [random.randrange(15, 30) for i in range(1)]
total_leucocyto = [random.randrange(2000, 20000) for i in range(1)]
left_deviation = [random.choice(['0', '1']) for i in range(1)]
sistolic_arterial_pressure = [random.randrange(60, 130) for i in range(1)]
average_arterial_pressure = [random.randrange(40, 80) for i in range(1)]
oliguria = [random.uniform(0.25, 0.75) for i in range(1)]
creatinine = [random.uniform(0.5, 3.0) for i in range(1)]
pao2_fio2_relation = [random.randrange(150, 400) for i in range(1)]
spo2 = [random.choice(['0', '1']) for i in range(1)]
platelet = [random.randrange(50000, 200000) for i in range(1)]
lactate = [random.choice(['0', '1']) for i in range(1)]
consciousness_status = [random.randrange(0, 1) for i in range(1)]
bilirubin = [random.choice(['0', '1']) for i in range(1)]

test = pd.DataFrame({
                   'central_temperature' : central_temperature,
                   'cardio_frequency' : cardio_frequency,
                   'resp_frequency' : resp_frequency,
                   'total_leucocyto' : total_leucocyto,
                   'left_deviation' : left_deviation,
                   'sistolic_arterial_pressure' : sistolic_arterial_pressure,
                   'average_arterial_pressure' : average_arterial_pressure,
                   'oliguria' : oliguria,
                   'creatinine' : creatinine,
                   'pao2_fio2_relation' : pao2_fio2_relation,
                   'spo2' : spo2,
                   'platelet' : platelet,
                   'lactate' : lactate,
                   'consciousness_status' : consciousness_status,
                   'bilirubin' : bilirubin})
test

,central_temperature,cardio_frequency,resp_frequency,total_leucocyto,left_deviation,sistolic_arterial_pressure,average_arterial_pressure,oliguria,creatinine,pao2_fio2_relation,spo2,platelet,lactate,consciousness_status,bilirubin
0,40,96,21,4329,0,97,68,0.477687,2.093167,273,1,91915,1,0,0

In [149]:
classifier_dt.predict(test)

array(['organic_disfunction'], dtype=object)

In [154]:

from sklearn.model_selection import cross_val_score

scores_dt = cross_val_score(classifier_dt, ft, outcome, scoring = 'accuracy', cv=5)

print(scores_dt.mean())

0.5700163398692811