In [1]:
import pandas as pd
import numpy as np
import time
import random
import datetime

In [14]:
central_temperature = [random.randrange(35, 41) for i in range(100)]
cardio_frequency = [random.randrange(60, 180) for i in range(100)]
resp_frequency = [random.randrange(15, 30) for i in range(100)]
total_leucocyto = [random.randrange(2000, 20000) for i in range(100)]
left_deviation = [random.choice(['0', '1']) for i in range(100)]
sistolic_arterial_pressure = [random.randrange(60, 130) for i in range(100)]
average_arterial_pressure = [random.randrange(40, 80) for i in range(100)]
oliguria = [random.uniform(0.25, 0.75) for i in range(100)]
creatinine = [random.uniform(0.5, 3.0) for i in range(100)]
pao2_fio2_relation = [random.randrange(150, 400) for i in range(100)]
spo2 = [random.choice(['0', '1']) for i in range(100)]
platelet = [random.randrange(50000, 200000) for i in range(100)]
lactate = [random.choice(['0', '1']) for i in range(100)]
consciousness_status = [random.randrange(0, 1) for i in range(100)]
bilirubin = [random.choice(['0', '1']) for i in range(100)]
user_id = [random.randrange(1, 5) for i in range(100)]
pacient_id = [i for i in range(100)]
created_at = [datetime.datetime.now() for i in range(100)]
updated_at = [datetime.datetime.now() for i in range(100)]

In [17]:
df = pd.DataFrame({'central_temperature' : central_temperature,
                   'cardio_frequency' : cardio_frequency,
                   'resp_frequency' : resp_frequency,
                   'total_leucocyto' : total_leucocyto,
                   'left_deviation' : left_deviation,
                   'sistolic_arterial_pressure' : sistolic_arterial_pressure,
                   'average_arterial_pressure' : average_arterial_pressure,
                   'oliguria' : oliguria,
                   'creatinine' : creatinine,
                   'pao2_fio2_relation' : pao2_fio2_relation,
                   'spo2' : spo2,
                   'platelet' : platelet,
                   'lactate' : lactate,
                   'consciousness_status' : consciousness_status,
                   'bilirubin' : bilirubin,
                   'user_id' : user_id,
                   'pacient_id' : pacient_id,
                   'created_at' : created_at,
                   'updated_at' : updated_at})

In [18]:
df

,central_temperature,cardio_frequency,resp_frequency,total_leucocyto,left_deviation,sistolic_arterial_pressure,average_arterial_pressure,oliguria,creatinine,pao2_fio2_relation,spo2,platelet,lactate,consciousness_status,bilirubin,user_id,pacient_id,created_at,updated_at
0,37,176,29,8009,1,98,68,0.414736,1.544906,220,1,100675,1,0,1,2,0,2019-03-31 05:59:23.130839,2019-03-31 05:59:23.131017
1,37,131,28,3876,0,126,72,0.716996,2.438961,280,0,66078,0,0,1,3,1,2019-03-31 05:59:23.130844,2019-03-31 05:59:23.131019
2,38,137,17,4982,0,124,77,0.426000,1.197045,226,1,175855,1,0,0,1,2,2019-03-31 05:59:23.130845,2019-03-31 05:59:23.131020
3,38,148,24,12810,1,60,69,0.310701,2.796376,230,1,56240,0,0,0,1,3,2019-03-31 05:59:23.130846,2019-03-31 05:59:23.131021
4,39,71,20,10516,1,64,63,0.604048,2.141140,214,1,134809,1,0,0,4,4,2019-03-31 05:59:23.130847,2019-03-31 05:59:23.131022
5,37,157,29,5871,1,105,59,0.550058,1.856384,369,1,91225,0,0,1,1,5,2019-03-31 05:59:23.130849,2019-03-31 05:59:23.131023
6,35,165,21,3830,0,65,50,0.505412,1.094998,208,0,81579,0,0,0,4,6,2019-03-31 05:59:23.130849,2019-03-31 05:59:23.131024
7,35,128,20,8068,1,79,64,0.448801,1.351790,200,1,103181,0,0,1,2,7,2019-03-31 05:59:23.130850,2019-03-31 05:59:23.131025
8,40,178,29,14240,0,97,49,0.645267,2.135191,309,0,160246,0,0,0,2,8,2019-03-31 05:59:23.130851,2019-03-31 05:59:23.131025
9,35,60,24,12902,0,81,50,0.740608,2.293938,346,0,113229,0,0,1,3,9,2019-03-31 05:59:23.130852,2019-03-31 05:59:23.131026
10,40,124,20,6669,1,67,49,0.267379,2.342613,209,0,153290,1,0,0,1,10,2019-03-31 05:59:23.130853,2019-03-31 05:59:23.131027
11,40,151,26,18710,1,104,60,0.529791,1.568714,311,1,149021,0,0,1,1,11,2019-03-31 05:59:23.130854,2019-03-31 05:59:23.131028
12,35,96,25,7308,1,108,57,0.739047,1.205146,240,1,104409,0,0,1,3,12,2019-03-31 05:59:23.130855,2019-03-31 05:59:23.131029
13,39,80,27,12243,0,82,41,0.514664,1.052463,351,0,104057,0,0,1,3,13,2019-03-31 05:59:23.130856,2019-03-31 05:59:23.131030
14,37,148,20,17594,1,78,77,0.263221,1.907197,244,0,86289,1,0,1,2,14,2019-03-31 05:59:23.130857,2019-03-31 05:59:23.131031
15,37,130,19,17222,1,74,61,0.499270,0.508375,155,1,189741,0,0,0,2,15,2019-03-31 05:59:23.130857,2019-03-31 05:59:23.131032
16,36,95,29,12585,1,67,78,0.729193,1.991901,279,0,103317,1,0,0,3,16,2019-03-31 05:59:23.130858,2019-03-31 05:59:23.131033
17,40,158,29,16739,0,124,63,0.629333,0.734886,187,1,191463,1,0,1,3,17,2019-03-31 05:59:23.130859,2019-03-31 05:59:23.131034
18,35,82,18,8575,1,116,65,0.313994,1.974496,332,0,135329,0,0,0,2,18,2019-03-31 05:59:23.130860,2019-03-31 05:59:23.131035
19,40,63,23,9258,1,84,45,0.257615,1.315959,366,1,173160,0,0,0,1,19,2019-03-31 05:59:23.130861,2019-03-31 05:59:23.131035
20,37,138,29,4328,1,92,77,0.666249,0.598486,278,1,132069,0,0,1,4,20,2019-03-31 05:59:23.130862,2019-03-31 05:59:23.131036
21,37,78,15,6410,1,104,45,0.633705,2.575888,266,0,117614,1,0,1,1,21,2019-03-31 05:59:23.130863,2019-03-31 05:59:23.131037
22,37,110,27,17794,0,104,43,0.394673,1.992942,390,1,140939,1,0,1,4,22,2019-03-31 05:59:23.130864,2019-03-31 05:59:23.131038
23,38,168,26,4022,0,81,46,0.599248,1.146851,193,1,73309,1,0,1,4,23,2019-03-31 05:59:23.130865,2019-03-31 05:59:23.131039
24,39,86,20,13612,1,61,63,0.519561,1.788765,391,1,147471,1,0,1,2,24,2019-03-31 05:59:23.130866,2019-03-31 05:59:23.131040
25,36,111,18,3789,0,114,66,0.523016,1.085108,229,1,51678,1,0,0,1,25,2019-03-31 05:59:23.130866,2019-03-31 05:59:23.131041
26,40,126,28,15202,1,87,79,0.274408,1.234041,389,1,176652,0,0,0,1,26,2019-03-31 05:59:23.130867,2019-03-31 05:59:23.131042
27,40,101,20,13500,0,64,63,0.273604,2.888945,244,1,90665,0,0,0,3,27,2019-03-31 05:59:23.130868,2019-03-31 05:59:23.131043
28,37,87,18,10290,0,65,58,0.659157,2.910928,225,0,81798,1,0,0,4,28,2019-03-31 05:59:23.130869,2019-03-31 05:59:23.131044
29,39,74,15,10082,1,64,62,0.608924,1.304104,184,0,104126,1,0,0,2,29,2019-03-31 05:59:23.130870,2019-03-31 05:59:23.131045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,38,179,17,10269,0,70,77,0.613899,1.655691,232,0,138421,0,0,1,4,70,2019-03-31 05:59:23.130905,2019-03-31 05:59:23.131082
71,36,176,16,8273,1,80,65,0.568761,2.323751,382,1,167682,0,0,1,2,71,2019-03-31 05:59:23.130906,2019-03-31 05:59:23.131083
72,39,81,16,14740,1,104,46,0.636572,0.969778,381,0,81636,0,0,0,1,72,2019-03-31 05:59:23.130907,2019-03-31 05:59:23.131083
73,40,115,23,4618,1,83,75,0.707488,1.112555,299,0,99012,0,0,0,2,73,2019-03-31 05:59:23.130909,2019-03-31 05:59:23.131085
74,39,163,24,11006,0,74,72,0.578338,1.399262,359,1,64001,1,0,0,3,74,2019-03-31 05:59:23.130910,2019-03-31 05:59:23.131086
75,38,63,15,13629,0,119,59,0.558852,0.665012,181,1,147886,0,0,1,2,75,2019-03-31 05:59:23.130910,2019-03-31 05:59:23.131087
76,39,101,15,10497,1,129,60,0.382579,2.851753,326,1,117535,0,0,1,1,76,2019-03-31 05:59:23.130911,2019-03-31 05:59:23.131088
77,39,149,17,15138,1,119,68,0.747473,2.824519,386,0,128230,0,0,0,4,77,2019-03-31 05:59:23.130912,2019-03-31 05:59:23.131089
78,36,117,15,8662,1,111,52,0.456421,0.929935,333,0,57994,1,0,0,4,78,2019-03-31 05:59:23.130912,2019-03-31 05:59:23.131090
79,37,70,27,8596,0,91,52,0.731939,1.240343,354,1,69022,1,0,1,4,79,2019-03-31 05:59:23.130913,2019-03-31 05:59:23.131091
80,36,97,17,16668,1,63,54,0.392821,1.402989,279,1,166663,0,0,0,2,80,2019-03-31 05:59:23.130914,2019-03-31 05:59:23.131091
81,39,111,15,5768,1,118,41,0.714210,2.043127,160,1,154639,1,0,0,3,81,2019-03-31 05:59:23.130914,2019-03-31 05:59:23.131092
82,39,160,27,4646,1,111,51,0.720351,1.393466,277,0,83471,0,0,1,4,82,2019-03-31 05:59:23.130915,2019-03-31 05:59:23.131093
83,38,113,27,12836,1,77,69,0.361438,2.651626,372,1,191668,0,0,0,1,83,2019-03-31 05:59:23.130916,2019-03-31 05:59:23.131094
84,36,158,20,11720,1,111,75,0.666997,1.207100,211,1,139139,0,0,0,4,84,2019-03-31 05:59:23.130917,2019-03-31 05:59:23.131095
85,36,100,18,12738,1,61,56,0.700807,2.012639,270,1,58019,0,0,1,1,85,2019-03-31 05:59:23.130917,2019-03-31 05:59:23.131096
86,39,161,17,6970,0,70,56,0.683409,0.834737,287,0,163082,0,0,0,2,86,2019-03-31 05:59:23.130918,2019-03-31 05:59:23.131097
87,35,111,19,4383,1,102,65,0.272430,1.809346,298,0,154833,0,0,0,4,87,2019-03-31 05:59:23.130919,2019-03-31 05:59:23.131097
88,35,115,19,4372,1,129,44,0.292958,1.805113,271,1,124322,0,0,0,1,88,2019-03-31 05:59:23.130920,2019-03-31 05:59:23.131098
89,36,176,20,15743,1,97,79,0.558341,1.324016,388,1,177847,0,0,1,4,89,2019-03-31 05:59:23.130921,2019-03-31 05:59:23.131099
90,38,172,24,19521,0,60,72,0.375037,1.007139,216,0,136474,0,0,0,4,90,2019-03-31 05:59:23.130922,2019-03-31 05:59:23.131100
91,37,147,24,4373,0,95,42,0.532415,2.397839,186,1,188445,1,0,1,2,91,2019-03-31 05:59:23.130923,2019-03-31 05:59:23.131101
92,35,78,19,19041,1,75,41,0.371700,0.537029,302,1,73433,0,0,0,3,92,2019-03-31 05:59:23.130924,2019-03-31 05:59:23.131102
93,35,150,16,8656,0,119,58,0.256589,1.155380,270,0,76134,1,0,0,1,93,2019-03-31 05:59:23.130925,2019-03-31 05:59:23.131103
94,39,114,19,12472,1,113,40,0.296241,1.928436,365,0,53137,1,0,1,4,94,2019-03-31 05:59:23.130925,2019-03-31 05:59:23.131104
95,37,73,15,2461,1,83,77,0.496093,0.709807,268,0,72625,1,0,1,4,95,2019-03-31 05:59:23.130926,2019-03-31 05:59:23.131105
96,38,83,27,10664,1,85,54,0.727563,0.877943,280,0,152162,0,0,1,3,96,2019-03-31 05:59:23.130927,2019-03-31 05:59:23.131105
97,36,65,29,4565,1,81,77,0.545994,0.860758,293,1,162721,1,0,0,2,97,2019-03-31 05:59:23.130928,2019-03-31 05:59:23.131106
98,36,130,22,15581,0,124,47,0.258052,2.542500,234,1,126067,1,0,1,1,98,2019-03-31 05:59:23.130929,2019-03-31 05:59:23.131107
99,37,123,18,11377,0,121,54,0.705404,1.193367,198,1,122948,1,0,1,3,99,2019-03-31 05:59:23.130930,2019-03-31 05:59:23.131108

In [19]:
df.to_csv('patient_data.csv')